name: ci
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: ["3.10", "3.11", "3.12"]

        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install Docker Compose
              run: |
                sudo apt-get update
                sudo apt-get install -y docker-compose
            
            - name: Cria arquivo .env
              run: |
                echo DB_NAME_PROD=${{ secrets.DB_NAME_PROD }} >> .env
                echo DB_USER_PROD=${{ secrets.DB_USER_PROD }} >> .env
                echo DB_PASS_PROD=${{ secrets.DB_PASS_PROD }} >> .env
                echo DB_HOST_PROD=${{ secrets.DB_HOST_PROD }} >> .env
                echo DB_PORT_PROD=${{ secrets.DB_PORT_PROD }} >> .env
                echo PGADMIN_EMAIL=${{ secrets.PGADMIN_EMAIL }} >> .env
                echo PGADMIN_PASSWORD=${{ secrets.PGADMIN_PASSWORD }} >> .env
                echo GENERIC_TIMEZONE=${{ secrets.GENERIC_TIMEZONE }} >> .env

            - name: Docker Compose up
              run: docker-compose --env-file .env up --build -d

            - name: Test Models with pytest
              run: pytest tests/test_models.py 