name: ci
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: ["3.10", "3.11", "3.12"]

        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install Docker Compose
              run: |
                sudo apt-get update
                sudo apt-get install -y docker-compose
            
            - name: Build and run docker-compose
              env:
                DB_NAME_PROD: ${{ secrets.DB_NAME_PROD }}
                DB_USER_PROD: ${{ secrets.DB_USER_PROD }}
                DB_PASS_PROD: ${{ secrets.DB_PASS_PROD }}
                DB_HOST_PROD: ${{ secrets.DB_HOST_PROD }}
                DB_PORT_PROD: ${{ secrets.DB_PORT_PROD }}
                PGADMIN_EMAIL: ${{ secrets.PGADMIN_EMAIL }}
                PGADMIN_PASSWORD: ${{ secrets.PGADMIN_PASSWORD }}
                GENERIC_TIMEZONE: ${{ secrets.GENERIC_TIMEZONE }}
              run: docker-compose up --build -d

            - name: Test Models with pytest
              run: pytest tests/test_models.py 