name: ci
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: ["3.10", "3.11", "3.12"]

        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}

            - name: Build and run docker-compose
              run: |
                docker-compose up --build -d

            - name: Test Models with pytest
              run: pytest tests/test_models.py 